/** DemandIndex catalog product groups shown on the KPI CTA scroll list. */
export const DEMAND_INDEX_PRODUCT_GROUPS = [
  'Batteries',
  'Batteries, Automotive',
  'Batteries, HD/Commercial',
  'Batteries, Marine',
  'Batteries, Lawn & Garden',
  'Batteries, Powersport',
  'Batteries, Golf Cart',
  'Brake System',
  'Brake Friction',
  'Brake Pads',
  'Brake Shoes',
  'Brake Steel',
  'Brake Drums',
  'Brake Rotors',
  'Brake Calipers',
  'Brake Boosters & Master Cylinders',
  'Brake Boosters',
  'Brake Master Cylinders',
  'Brakes, ABS',
  'Sensors, ABS Wheel Speed',
  'Brakes, Misc. Hydraulics',
  'Brakes, Hardware',
  'Climate Control',
  'AC Compressors & Selected Components',
  'AC Components',
  'Blower Motors & Resistors',
  'Heater Core',
  'Connectors (New!)',
  'Cooling',
  'Hoses & Belts',
  'Hoses',
  'Belts',
  'Water Pumps',
  'Timing Belt Kits',
  'Thermostats & Water Outlets',
  'Radiators',
  'Radiator and Colling Fan Components',
  'Fan Assemblies',
  'Radiator Fan Clutches & Blades',
  'Driveline',
  'Bearings, Wheel Hubs & Seals',
  'Wheel Bearings',
  'Wheel Seals',
  'Wheel Hub Bearings',
  'Wheel Bearing and Seal Kits',
  'CV Axles',
  'Axle Components',
  'Clutch Kits & Components',
  'Clutch Kits',
  'Clutch Hydraulics',
  'Clutch Kits Components',
  'Electrical, Application',
  'Sensors, Engine Management',
  'Sensors, Emission',
  'Sensors, Oxygen',
  'Sensors, MAF & MAP/BAP',
  'Sensors, Position',
  'Sensors, Misc.',
  'Sensors, TPMS',
  'ADAS',
  'Window Lift Components',
  'Power Window Assembly',
  'Power Window Motor',
  'Motors & Actuators, Door Lock',
  'Motors & Actuators, Body',
  'Electrical, Rotating',
  'Charging Systems',
  'Alternators & Generators',
  'Starting Systems',
  'Starter Motors',
  'Emission Control & Air Management',
  'Emission',
  'EGR',
  'Air Injection/Smog Pumps',
  'Idle Air Systems',
  'Emission, Evaporative',
  'Emission, Misc.',
  'Turbo/Supercharger Kits & Components',
  'Turbo/Superchargers',
  'Intercoolers',
  'Catalytic Converters & Mufflers',
  'Catalytic Converters',
  'Mufflers',
  'Manifolds, Intake/Exhaust',
  'Manifolds, Exhaust',
  'Manifolds, Intake',
  'Engine Components',
  'Belt Tensioners & Idler Pulleys',
  'Accessory & A/C Tensioners & Pulleys',
  'Timing Belt Tensioners & Pulleys',
  'Timing Belts',
  'Timing Chains',
  'Timing, Variable Valve',
  'Engine & Transmission Mounts',
  'Filtration',
  'Filters, Air',
  'Filters, Cabin',
  'Filters, Fuel',
  'Filters, Oil',
  'Filters, Transmission',
  'Fluids',
  'Fluids, Motor Oils',
  'Fluids, PCMO Conventional',
  'Fluids, PCMO Conventional High Mileage',
  'Fluids, PCMO Full Synthetic',
  'Fluids, PCMO Full Synthetic High Mileage',
  'Fluids, HDMO',
  'Fluids, Coolant & Antifreeze',
  'Fluids, Hydraulic',
  'Fluids, ATF',
  'Fluids, DEF',
  'Fuel System',
  'Fuel Pumps & Components',
  'Fuel Pumps,  Mechanical',
  'Fuel Pumps, Electrical',
  'Fuel Pumps Components',
  'Fuel Pump Assembly',
  'Fuel Injection',
  'Fuel Injector',
  'Throttle Body',
  'Gaskets',
  'Gaskets, Engine',
  'Gaskets, Exhaust',
  'Gaskets, Driveline/Transmission',
  'Gaskets, Fuel System',
  'Gaskets, Cooling',
  'Gaskets, Misc.',
  'Ignition System',
  'Ignition Components',
  'Ignition, Electronic',
  'Ignition, Coils',
  'Ignition, Module/Control Units & Pick-Up Assemblies',
  'Ignition, Conventional',
  'Lighting',
  'Taillight Assemblies',
  'Headlight Assemblies',
  'Headlight Halogen Capsule',
  'Relays (New!)',
  'Spark Plugs',
  'Steering',
  'Power Steering',
  'Power Steering Pumps',
  'Power Steering Pumps Electric',
  'Rack and Pinion Assembly',
  'Power Steering Gears',
  'Power Steering, Misc.',
  'Power Steering Hoses, Lines & Fittings',
  'Tie Rods, Steering Linkage & Stabilizing',
  'Suspension',
  'Suspension Components',
  'Ball Joints & Components',
  'Control Arms',
  'Ride Control Suspension',
  'Shocks',
  'Struts',
  'Struts, Loaded',
  'Struts, Bare',
  'Air Springs & Components',
  'Switches (New!)',
  'Wipers',
  'Windshield Wiper Blade, Beam',
  'Windshield Wiper Blade, Conventional',
  'Windshield Wiper Blade, Hybrid',
  'Windshield Wiper Blade, Winter',
  'Windshield Wiper, Back Glass',
  'Windshield Wiper Blade, Refill',
] as const;

export const DEMAND_INDEX_PRODUCT_LIST_SCROLL_MS = 3000;
